server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: none
  application:
    name: site-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.typ.descriptor.sql.BasicBinder: TRACE